### ISSUE TITLE
Logo on the homepage has a strange background colour

### ISSUE THREAD

**Issue by akcasoy** [Teamtool/teamtool-mean#10]
We have to find why the logo on the homepage has a strange background colour. We don't have this problem on local server. Also that is ensured that this problem isn'T caused by the recent refactoring of the main controller.

**Comment by MilenkoBugueno** [comment]
This problem is present also on the local server but only in production mode. I think this issue depends on the different dependencies between development and production.

**Comment by akcasoy** [comment]
readonly attribute of the uib-rating component (stars) is also not working on production (unauthorised users can click on stars). Similar issue i think.

**Comment by MilenkoBugueno** [comment]
For some reason imagemin is changing the color of the PNG when minimizing. I tried different optimization levels but it didn't work. 
I changed the logo to a transparent one
