### ISSUE TITLE
Navbar binding problem

### ISSUE THREAD

**Issue by akcasoy** [Teamtool/teamtool-mean#6]
Navbar has an "Hello username" message. This shows the actual user only after a refresh. Without refresh the previous user is shown. I think this refactoring f61d00025a6f3b7d6416793653edef5867e97255 caused the problem.

**Comment by MilenkoBugueno** [comment]
Actually it was a reference error for ng-model. ng-model cannot be 0
https://docs.angularjs.org/error/ngModel/nonassign?p0=0&p1=

**Comment by akcasoy** [comment]
I don't think that commit dfb2192dd7b544148b3632c5b9124c0467191c89 does have sth to do with the actual problem..

**Comment by MilenkoBugueno** [comment]
I think the errors are responsible for this issue.
We have three error types:
- Reference error for n-model: fixed
- Undefined is not an object (evaluating 'b.length')
- Failed to load resource: the server responded with a status 401/404

I am creating separate issues for them.

**Comment by akcasoy** [comment]
Those errors are not the reason of this error. Please read the description of comment c8f7e18b1bdce8bff19632fc73e7eb98c166f836. We had a similar problem that time. In navbar.controller.js the current user must be read as a callback, not as an attribute. I will fix this issue.
