### ISSUE TITLE
Error: undefined is not an object (evaluating 'b.length')

### ISSUE THREAD

**Issue by MilenkoBugueno** [Teamtool/teamtool-mean#7]
In production we have following error: Error: undefined is not an object (evaluating 'b.length')

I think the function descLimitFilter is responsible for it:

    function descLimitFilter(a) {
        return function(b, c) {
            return c || b.length < 280 ? b : a("limitTo")(b, 230) + " ....."
        }
    }

**Comment by akcasoy** [comment]
This is not a bug. There is an old idea from Resa, and it does not have a description. Since the title, description and category are mandatory fields, this error does not appear when i set a description text to this idea document in db.
