### ISSUE TITLE
Failed to load resource: the server responded with a status of 401/404

### ISSUE THREAD

**Issue by MilenkoBugueno** [Teamtool/teamtool-mean#8]
We have following error in production
Failed to load resource: the server responded with a status of 401 (Unauthorized) http://localhost:9000/api/users/me
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:9000/api/things
Failed to load resource: the server responded with a status of 401 (Unauthorized) http://localhost:9000/auth/local

**Comment by akcasoy** [comment]
The above commit will very likely fix the error 404. 

The other 401 (Unauthorized) error i just see when i intentionally type sth false by logging in. And I do not know whether we should still clear those error logs..

We also see this error bei signing up when we try to sign up with an already specified username / email:
Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)

**Comment by MilenkoBugueno** [comment]
You are right. I think I forgot to clear my log :)
